# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Golang CGO cross compiler'
description: 'GitHub Action for xgo, a Golang CGO cross compiler'
author: 'crazy-max'
branding:
  color: 'green'
  icon: 'package'

inputs:
  go_version:
    description: 'Go release to use for cross compilation. Example: 1.12.x'
    default: 'latest'
  dest:
    description: 'Destination folder to put binaries in'
    default: 'build'
  prefix:
    description: 'Prefix to use for output naming. Default to package name'
  targets:
    description: 'Comma separated targets to build for. Example: windows/amd64,linux/386'
    default: '*/*'
  v:
    description: 'Prints the names of packages as they are compiled'
    default: 'false'
  x:
    description: 'Prints the build commands as compilation progresses'
    default: 'false'
  ldflags:
    description: 'Arguments to pass on each go tool link invocation'

runs:
  using: 'node12'
  main: 'lib/xgo.js'
