name: ci

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  pull_request:
    branches:
      - master
      - releases/v*
  push:
    branches:
      - master
      - releases/v*

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.14.x
          - 1.15.x
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Xgo
        uses: ./
        with:
          go_version: ${{ matrix.go_version }}
          targets: windows/386,windows/amd64,linux/386,linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,darwin/386,darwin/amd64
          v: true
          x: false
          ldflags: -s -w
      -
        name: Check
        run: |
          sudo apt-get -qq install tree
          tree -f -h ./build
